"use strict";

// Strip noise from ABAP source code so the LLM context burns fewer tokens.
//
// Three levels (cumulative — each builds on the previous):
//
//   light       (~ 5-10% saved)
//                - collapse runs of >=2 blank lines into one
//                - trim trailing whitespace on every line
//
//   medium      (~20-35% saved)
//                light + remove full-line star comments at col 1 ("*..."),
//                       UNLESS they look like ABAPDoc ("*!..."), and
//                       trailing inline comments (' " text' after a code stmt)
//
//   aggressive  (~30-45% saved)
//                medium + drop boilerplate banners:
//                       - "* Generated by ..."
//                       - "* DO NOT (MODIFY|EDIT)"
//                       - "*&-+", "*-+" banner separators
//                       - empty banner lines like just "*"
//
// Translatable text literals ('text'(001)) are NEVER touched — they carry
// load-bearing semantics.

const LEVELS = new Set(["light", "medium", "aggressive"]);
const DEFAULT_LEVEL = "medium";

function isLevel(level) {
  return LEVELS.has(level);
}

function strip(source, level) {
  if (source == null) return "";
  const lvl = LEVELS.has(level) ? level : DEFAULT_LEVEL;
  const lines = String(source).split(/\r?\n/);

  const out = [];
  let pendingBlank = false;

  for (let line of lines) {
    // Always: trim trailing whitespace.
    line = line.replace(/[ \t]+$/g, "");

    if (lvl !== "light") {
      // medium + aggressive: strip full-line comments and inline comments.
      const trimmed = line.replace(/^\s+/, "");

      // Full-line comment guard. Keep ABAPDoc ("*!" or "\"!").
      if (/^\*(?!!)/.test(trimmed)) {
        if (lvl === "aggressive" && _isBoilerplate(trimmed)) {
          // drop entirely
          continue;
        } else if (lvl === "aggressive") {
          // medium-level rule: drop generic star comments too
          continue;
        } else {
          // medium: drop generic star comments but keep ABAPDoc.
          continue;
        }
      }

      // Strip inline trailing comment "code ... " text". The quote-aware
      // regex tolerates string literals using single quotes.
      line = _stripInlineQuoteComment(line);
    }

    // Drop ABAP-style empty banner lines on aggressive ("*" alone).
    if (lvl === "aggressive") {
      const trimmed = line.replace(/^\s+/, "");
      if (/^\*\s*$/.test(trimmed)) continue;
    }

    // Blank-line collapse (all levels): >=2 blanks -> 1.
    if (line.trim() === "") {
      if (pendingBlank) continue;
      pendingBlank = true;
      out.push("");
      continue;
    }
    pendingBlank = false;
    out.push(line);
  }

  return out.join("\n");
}

function _isBoilerplate(trimmed) {
  if (/^\*\s*generated\s+by\b/i.test(trimmed)) return true;
  if (/^\*\s*do\s+not\s+(modify|edit)\b/i.test(trimmed)) return true;
  if (/^\*&-+$/.test(trimmed)) return true;
  if (/^\*-+$/.test(trimmed)) return true;
  if (/^\*&\s*$/.test(trimmed)) return true;
  return false;
}

// Walk the line and drop everything from an unquoted " to the end of line.
// ABAP string literals can use ' or `. Inline comments only start with ".
function _stripInlineQuoteComment(line) {
  let inSingle = false;
  let inBacktick = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === "'" && !inBacktick) inSingle = !inSingle;
    else if (c === "`" && !inSingle) inBacktick = !inBacktick;
    else if (c === '"' && !inSingle && !inBacktick) {
      // Inline comment start — drop from here on. Preserve any preceding
      // whitespace-trimmed code segment.
      return line.slice(0, i).replace(/[ \t]+$/g, "");
    }
  }
  return line;
}

// Cheap savings estimator: drop comments + collapse blanks, report char counts.
function estimateSavings(source, level) {
  const stripped = strip(source, level);
  return {
    before: source.length,
    after: stripped.length,
    saved: source.length - stripped.length,
    ratio: source.length === 0 ? 0 : (source.length - stripped.length) / source.length,
  };
}

module.exports = {
  strip,
  isLevel,
  estimateSavings,
  DEFAULT_LEVEL,
  LEVELS: Array.from(LEVELS),
};
